DELETE FROM BATCH_STEP_EXECUTION_CONTEXT ;
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT ;
DELETE FROM BATCH_STEP_EXECUTION ;
DELETE FROM BATCH_JOB_EXECUTION_PARAMS ;
DELETE FROM BATCH_JOB_EXECUTION ;
DELETE FROM BATCH_JOB_INSTANCE ;
DELETE FROM BATCH_STEP_EXECUTION_SEQ ;
DELETE FROM BATCH_JOB_EXECUTION_SEQ ;
DELETE FROM BATCH_JOB_SEQ ;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_STEP_EXECUTION_SEQ);
INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_EXECUTION_SEQ);
INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_SEQ);

COMMIT
